config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "", path_names: {
    sign_in: "login",
    sign_out: "logout",
    password: "secret",
    confirmation: "verification",
    unlock: "unblock",
    sign_up: "sign_up"
  }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "dashboard#index"

  resources :crawl_markets do
    resources :crawler_fields
  end

  resources :exchange_rates
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/crawl_market.rb
class CrawlMarket < ApplicationRecord
  serialize :crawler_paths, coder: YAML, type: Array

  has_many :crawler_fields, dependent: :destroy

  validates :name, :code, :crawler_paths, presence: true
  validates :name, :code, uniqueness: true

  accepts_nested_attributes_for :crawler_fields, allow_destroy: true

  before_save :remove_blank_paths

  def self.display_fields
    CrawlMarket.column_names - [
      "created_at",
      "updated_at",
      "price_tag_container",
      "create_order_btn_container"
    ]
  end

  def crawler_paths_normalize
    crawler_paths.map(&:values).flatten.join(", ")
  end

  private

  def remove_blank_paths
    self.crawler_paths = crawler_paths.reject(&:blank?)
  end
end

app/models/crawler_field.rb
class CrawlerField < ApplicationRecord
  serialize :selector, type: Array, coder: YAML

  enum :query_type, {
    class_relative: I18n.t("crawler_field.query_type_options.class_relative"),
    exactly_match: I18n.t("crawler_field.query_type_options.exactly_match"),
    url_search_param: I18n.t("crawler_field.query_type_options.url_search_param"),
    url_search_param_from_element: I18n.t("crawler_field.query_type_options.url_search_param_from_element"),
  }, default: :class_relative

  belongs_to :crawl_market
  validates :field_name, :selector, :query_type, :element_content_attr, presence: true
  validates :field_name, uniqueness: { scoped: [:crawl_market_id] }

  def selector_normalize
    selector.map do |i|
      i.is_a?(String) ? i : i.values
    end.flatten.join(", ")
  end
end

app/models/exchange_rate.rb
class ExchangeRate < ApplicationRecord
  SUPPORTED_CURRENCIES = %i[usd eur cny vnd]

  validates :currency_code, :rate, presence: true
  validates :currency_code, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :trackable

  has_one_attached :avatar, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include CableReady::Broadcaster
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  layout :layout_by_resource

  private

  def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end
  end
end

app/controllers/crawl_markets_controller.rb
class CrawlMarketsController < ApplicationController
  before_action :authenticate_user!
  def index
    @crawl_markets = CrawlMarket.all
  end

  def edit
    @crawl_market = CrawlMarket.find(params[:id])
  end

  def create
    @crawl_market = CrawlMarket.new(crawl_market_params)
    @crawl_market.crawler_paths = JSON.parse crawl_market_paths rescue crawl_market_paths

    if @crawl_market.save
      flash.now[:notice] = "Market created successfully"
      render :create
    else
      render(turbo_stream: turbo_stream.update(
        :crawl_market_errors,
        partial: "shared/errors",
        locals: { errors: @crawl_market.errors.full_messages.join("\n") }
      ))
    end
  end

  def update
    @crawl_market = CrawlMarket.find(params[:id])
    crawler_paths = JSON.parse(crawl_market_paths) rescue @crawl_market.crawler_paths.presence || crawl_market_paths

    if @crawl_market.update(crawl_market_params.merge(crawler_paths:))
      flash.now[:notice] = "Market updated successfully"
    else
      flash.now[:alert] = "#{@crawl_market.errors.full_messages.join(', ')}"
    end
  end

  def destroy
    @crawl_market = CrawlMarket.find(params[:id])

    if @crawl_market.destroy
      flash.now[:notice] = "Market deleted successfully"
    else
      flash.now[:alert] = "#{@crawl_market.errors.full_messages.join(', ')}"
    end
  end

  private

  def crawl_market_params
    params.require(:crawl_market).permit(
      :name, :code, :enabled,
      :create_order_btn_container,
      :price_tag_container,
      crawler_paths: []
    )
  end

  def crawl_market_paths
    params.require(:crawl_market).fetch(:crawler_paths, [])
  end
end

app/controllers/crawler_fields_controller.rb
class CrawlerFieldsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_crawl_market

  def index; end

  def create
    selector = JSON.parse selector_params rescue []
    @crawler_field = @crawl_market.crawler_fields.build(crawler_field_params.merge(selector:))

    if @crawler_field.save
      flash.now[:notice] = "Crawler field created successfully."
    else
      flash.now[:alert] = "Crawler field create failure. #{@crawler_field.errors.full_messages}"
    end
  end

  def update
    selector = JSON.parse selector_params rescue []
    @crawler_field = @crawl_market.crawler_fields.find(params[:id])

    if @crawler_field.update(crawler_field_params.merge(selector:))
      flash.now[:notice] = "Crawler field updated successfully."
    else
      flash.now[:alert] = "Crawler field update failure."
    end
  end

  private

  def load_crawl_market
    @crawl_market = CrawlMarket.find(params[:crawl_market_id])
  end

  def selector_params
    params.require(:crawler_field).fetch(:selector, [])
  end

  def crawler_field_params
    params.require(:crawler_field).permit(
      :field_name,
      :query_type,
      :element_content_attr,
      selector: []
    )
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index

  end
end

app/controllers/exchange_rates_controller.rb
class ExchangeRatesController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sidebar_items
    [
      {
        title: "Setting",
        icon_name: "cog",
        active_class: nil,
        url: root_path
      },
      {
        title: "Exchange Rates",
        icon_name: "dollar-circle",
        active_class: ["exchange_rates"].include?(controller_name) ? "menu-active" : nil,
        url: exchange_rates_path
      },
      {
        title: "Crawl Markets",
        icon_name: "archive",
        active_class: ["crawl_markets", "crawler_fields"].include?(controller_name) ? "menu-active" : nil,
        url: crawl_markets_path
      },
      {
        title: "Bank Account",
        icon_name: "bank",
        icon_type: "solid",
        active_class: nil,
        url: root_path
      }
    ]
  end
end

app/helpers/crawler_fields_helper.rb
module CrawlerFieldsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/crawl_markets/_edit_form.html.erb
<%= turbo_frame_tag :edit_crawl_market_frame do %>
  <dialog id="edit_crawl_market_dialog" class="modal modal-bottom sm:modal-middle" open>
    <div class="modal-box">
      <form method="dialog">
        <button class="btn btn-sm btn-circle btn-ghost absolute right-2 top-2">✕</button>
      </form>
      <div class="dialog-header mb-5">
        <h4 class="text-lg font-bold">Edit Crawl Market</h4>
      </div>
      <%= render "form",
        crawl_market: crawl_market,
        form_url: crawl_market_path(crawl_market),
        form_method: :patch
      %>
    </div>
  </dialog>
<% end %>

app/views/crawl_markets/_form.html.erb
<div class="form-container">
  <%= form_for crawl_market, url: form_url, html: { class: "text-sm" }, data: { turbo_method: form_method } do |f| %>
    <div class="space-y-2">
      <div class="mb-4 flex items-center justify-start gap-4">
        <legend class="fieldset-legend text-sm min-w-24">Code:</legend>
        <label class="input input-md w-full rounded-xl">
          <%= f.text_field :code, autofocus: true, class: "grow", placeholder: "Code" %>
        </label>
      </div>

      <div class="mb-4 flex items-center justify-start gap-4">
        <legend class="fieldset-legend text-sm min-w-24">Name:</legend>
        <label class="input input-md w-full rounded-xl">
          <%= f.text_field :name, autofocus: true, class: "grow", placeholder: "Name" %>
        </label>
      </div>

      <div class="mb-0 flex items-center justify-start gap-4">
        <legend class="fieldset-legend text-sm min-w-24">Crawl Paths:</legend>
        <label class="input input-md w-full rounded-xl p-0 h-auto">
          <%= f.text_field :crawler_paths, value: crawl_market.crawler_paths.to_json, autofocus: true, class: "grow !border-0", placeholder: "Paths", data: { controller: "tagify" } %>
        </label>
      </div>
      <div class="text-xs pl-30 mb-4 font-normal mt-1">
        value should be a host, separated by `tab`
      </div>
      <div class="mb-4 flex items-center justify-start gap-4">
        <legend class="fieldset-legend text-sm min-w-24">Enabled:</legend>
        <%= f.check_box :enabled, class: "toggle" %>
      </div>
    </div>

    <div class="modal-action">
      <%= turbo_frame_tag :crawl_market_errors, class: "flex flex-1" %>
      <button class="btn btn-success text-white px-8">Save</button>
    </div>
  <% end %>
</div>

app/views/crawl_markets/_list.html.erb
<%= turbo_frame_tag :crawl_market_list do %>
  <div class="overflow-x-auto rounded-box border border-base-content/5 bg-base-100" data-theme="caramellatte">
    <table class="table">
      <!-- head -->
      <thead>
        <tr>
          <% CrawlMarket.display_fields.each do |column_name| %>
            <th><%= column_name.humanize.titlecase %></th>
          <% end %>
          <th class="w-25">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% if CrawlMarket.all.present? %>
          <% CrawlMarket.all.each do |crawl_market| %>
            <tr class="hover:bg-base-300 cursor-pointer">
              <th><%= crawl_market.id %></th>
              <td><%= crawl_market.code %></td>
              <td><%= crawl_market.name %></td>
              <td><%= crawl_market.crawler_paths_normalize %></td>
              <td>
                <input
                  type="checkbox"
                  <%= crawl_market.enabled ? "checked" : "" %>
                  class="toggle toggle-md"
                  data-reflex="click->CrawlMarketReflex#toggle"
                  data-id="<%= crawl_market.id %>"
                />
              </td>
              <td class="w-35">
                <div>
                  <%= link_to crawl_market_crawler_fields_path(crawl_market), class: "btn btn-success btn-sm btn-square", data: { turbo: false } do %>
                    <%= icon "sitemap", class: "fill-primary-content" %>
                  <% end %>
                  <%= link_to edit_crawl_market_path(crawl_market),
                    class: "btn btn-accent btn-sm btn-square",
                    data: {
                      turbo_method: :get,
                      turbo_frame: "edit_crawl_market_frame"
                    } do %>
                    <%= icon "edit", class: "fill-accent-content" %>
                  <% end %>
                  <%= link_to crawl_market_path(crawl_market),
                    class: "btn btn-error btn-sm btn-square",
                    data: {
                      turbo_confirm: "Are you sure you want to delete the crawl market?",
                      turbo_method: :delete
                    } do %>
                    <%= icon "trash", class: "fill-error-content" %>
                  <% end %>
                </div>
              </td>
            </tr>
          <% end %>
        <% else %>
          <tr>
            <td colspan="<%= CrawlMarket.display_fields.size + 1 %>">
              <div class="flex items
              -center justify-center space-x-2">
                <%= icon "archive", class: "fill-base-content" %>
                <span>No crawl markets found</span>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/crawl_markets/_new_form.html.erb
<%= turbo_frame_tag :new_crawl_market_frame do %>
  <dialog id="new_crawl_market_dialog" class="modal modal-bottom sm:modal-middle">
    <div class="modal-box">
      <form method="dialog">
        <button class="btn btn-sm btn-circle btn-ghost absolute right-2 top-2">✕</button>
      </form>
      <div class="dialog-header mb-5">
        <h4 class="text-lg font-bold">New Crawl Market</h4>
      </div>
      <div class="form-container">
        <%= render "form",
          crawl_market: CrawlMarket.new,
          form_url: crawl_markets_path,
          form_method: :post
        %>
      </div>
    </div>
  </dialog>
<% end %>

app/views/crawl_markets/_update_and_toast_message.html.erb
<%= turbo_stream.replace :toast do %>
 <%= render "layouts/toast" %>
<% end %>
<%= turbo_stream.replace :crawl_market_list do %>
  <%= render "crawl_markets/list" %>
<% end %>

app/views/crawl_markets/create.turbo_stream.erb
<%= turbo_stream.update :dump do %>
  <script type="module">
    document.querySelector('#new_crawl_market_dialog [method="dialog"] button').click();
  </script>
<% end %>

<%= turbo_stream.replace :new_crawl_market_frame do %>
  <%= render "crawl_markets/new_form" %>
<% end %>

<%= turbo_stream.replace :crawl_market_list do %>
  <%= render "crawl_markets/list" %>
<% end %>

<%= turbo_stream.replace :toast do %>
  <%= render "layouts/toast" %>
<% end %>

app/views/crawl_markets/destroy.turbo_stream.erb
<%= render "update_and_toast_message" %>

app/views/crawl_markets/edit.html.erb
<%= render "edit_form", crawl_market: @crawl_market %>

app/views/crawl_markets/index.html.erb
<div class="text-xl font-bold flex items-center justify-between space-x-2 flex-row cursor-default mb-5">
  <div class="flex items-center space-x-2 flex-row">
    <%= icon "archive" %>
    <span>Crawl Markets</span>
  </div>
  <div>
    <button class="btn" onclick="new_crawl_market_dialog.showModal()">
      <%= icon "plus" %>
      <span>New</span>
    </button>
    <%= render "new_form" %>
  </div>
</div>
<%= render "list" %>
<%= turbo_frame_tag :edit_crawl_market_frame %>

app/views/crawl_markets/update.turbo_stream.erb
<%= render "update_and_toast_message" %>
<%= turbo_stream.update :dump do %>
  <script type="module">
    document.querySelector('#edit_crawl_market_dialog [method="dialog"] button').click();
  </script>
<% end %>

app/views/crawler_fields/_form.html.erb
<%= form_for resource, url: resource_path, method: resource_method, html: { class: "space-y-5", id: resource_submit_id } do |f| %>
  <div class="flex flex-row space-x-4">
    <label class="floating-label w-2/6">
      <%= f.text_field :field_name, class: "input input-md bg-primary-content", placeholder: "Field Name *" %>
      <span>Field Name <span class="required font-weight-bold text-red-600">*</span></span>
    </label>

    <label class="select w-4/6 bg-primary-content">
      <span class="label">Query Type <span class="required font-weight-bold text-red-600">*</span></span>
      <%= f.select :query_type, CrawlerField.query_types.invert.to_a, {} %>
    </label>

    <label class="floating-label w-1/3">
      <%= f.text_field :element_content_attr, class: "input input-md bg-primary-content", placeholder: "Element Content Attribute *" %>
      <span>Element Content Attribute <span class="required font-weight-bold text-red-600">*</span></span>
    </label>
  </div>
  <div data-controller="tagify">
    <label class="w-full text-sm">
      <span class="inline-block mb-3">Selectors <span class="required font-weight-bold text-red-600">*</span></span>
    </label>
    <%= f.text_field :selector, value: resource.selector_normalize, class: "customLook text-sm", placeholder: "Selectors *" %>
    <button type="button" data-action="click->tagify#onAddNewTag">+</button>
  </div>
<% end %>

app/views/crawler_fields/_item.html.erb
<%= turbo_frame_tag "crawler_field_#{crawler_field.to_gid_param}", class: "block" do %>
  <div class="bg-base-100 border-base-300 collapse border text-base-content" data-theme="caramellatte">
    <%= radio_button "crawl-market-#{@crawl_market.to_gid_param}", nil, nil,
      class: "collapse-radio", checked: selected_id == crawler_field.to_gid_param
    %>
    <div class="collapse-title flex flex-row items-center justify-between pr-4">
      <p class="text-neutral">Crawler Field: <%= crawler_field.field_name %></p>
      <div class="collapse-hidden flex flex-row gap-2 z-100">
        <button class="btn btn-sm btn-accent z-100" form="crawler_field_form_for_<%= crawler_field.to_gid_param %>">
          <%= icon "save", class: "w-5 h-5 fill-current" %>
          <span class="text-sm">Save</span>
        </button>
        <%= link_to crawl_market_crawler_field_path(@crawl_market, crawler_field),
          class: "btn btn-sm z-100",
          data: {
            reflex: "click->CrawlerField#destroy",
            crawler_field: crawler_field.id,
            crawl_market: @crawl_market.id
          } do
        %>
          <%= icon "trash", class: "w-5 h-5" %>
          <span class="text-sm">Delete</span>
        <% end %>
      </div>
    </div>
    <div class="collapse-content">
      <%= render "form",
        resource: crawler_field,
        resource_path: crawl_market_crawler_field_path(@crawl_market, crawler_field),
        resource_method: :patch,
        resource_submit_id: "crawler_field_form_for_#{crawler_field.to_gid_param}"
      %>
    </div>
  </div>
<% end %>

app/views/crawler_fields/_list.html.erb
<%= turbo_frame_tag :crawler_fields_list do %>
  <div class="space-y-3">
    <%= render partial: "item",
      collection: @crawl_market.crawler_fields.order(id: :asc),
      as: :crawler_field,
      locals: { selected_id: selected_id }
    %>
  </div>
<% end %>

app/views/crawler_fields/_new_field.html.erb
<div class="divider divider-neutral">NEW</div>
<div class="bg-base-100 border-base-300 collapse border">
  <input type="radio" name="crawl-market-<%= @crawl_market.to_gid_param %>" checked/>
  <div class="collapse-title flex flex-row items-center justify-between pr-4 peer-checked:mb-3">
    <p>Crawler Field: <%= crawler_field.field_name %></p>
    <button class="btn btn-sm z-100" form="crawler_field_form_for">
      <%= icon "save", class: "w-5 h-5" %>
      <span class="text-sm">Save</span>
    </button>
  </div>
  <div class="collapse-content">
    <%= render "form",
      resource: crawler_field,
      resource_path: crawl_market_crawler_fields_path,
      resource_method: :post,
      resource_submit_id: "crawler_field_form_for" %>
  </div>
</div>

app/views/crawler_fields/create.turbo_stream.erb
<%= turbo_stream.replace :toast do %>
 <%= render "layouts/toast" %>
<% end %>

<% if @crawler_field.persisted? %>
  <%= turbo_stream.replace :crawler_fields_list do %>
    <%= render "crawler_fields/list", selected_id: @crawler_field.to_gid_param %>
  <% end %>

  <%= turbo_stream.update :new_crawler_field_form %>
<% end %>

app/views/crawler_fields/index.html.erb
<div class="text-xl font-bold flex items-center justify-between space-x-2 flex-row cursor-default mb-5">
  <div class="flex items-center space-x-2 flex-row">
    <%= link_to crawl_markets_path, class: "btn btn-sm btn-square mr-4" do %>
      <%= icon "arrow-back" %>
    <% end %>
    <%= icon "store", class: "w-8 h-8" %>
    <span><%= @crawl_market.name %></span>
  </div>
  <div>
    <%= link_to new_crawl_market_crawler_field_path, class: "btn", data: { turbo_stream: true } do %>
      <%= icon "list-plus" %>
      <span>New Field</span>
    <% end %>
  </div>
</div>

<div class="bg-base-100 border-base-300 collapse border text-base-content mb-3" data-theme="caramellatte">
  <%= radio_button "crawl-market-base", nil, nil, class: "collapse-radio", checked: true %>
  <div class="collapse-title flex flex-row items-center justify-between pr-4">
    <p class="text-neutral">Crawler Base Fields</p>
    <div class="collapse-hidden flex flex-row gap-2 z-100">
      <button class="btn btn-sm btn-accent z-100" form="update-crawl-market-<%= @crawl_market.to_gid_param %>">
        <%= icon "save", class: "w-5 h-5 fill-current" %>
        <span class="text-sm">Save</span>
      </button>
    </div>
  </div>
  <div class="collapse-content">
    <%= form_for @crawl_market, url: crawl_market_path(@crawl_market), method: :patch,
      html: { id: "update-crawl-market-#{@crawl_market.to_gid_param}" } do |f| %>
      <div class="flex flex-row items-center gap-4 mb-3 px-1">
        <label class="floating-label w-full" data-theme="caramellatte">
          <%= f.text_field :create_order_btn_container, class: "input input-md bg-primary-content w-full", placeholder: "Create Order button container *" %>
          <span>Create Order button container</span>
        </label>
        <label class="floating-label w-full" data-theme="caramellatte">
          <%= f.text_field :price_tag_container, class: "input input-md bg-primary-content w-full", placeholder: "Create Order button container *" %>
          <span>Price Tag container</span>
        </label>
      </div>
    <% end %>
  </div>
</div>

<%= render "list", selected_id: nil %>
<%= turbo_frame_tag :new_crawler_field_form %>

app/views/crawler_fields/new.turbo_stream.erb
<%= turbo_stream.update :new_crawler_field_form do %>
  <%= render "new_field", crawler_field: CrawlerField.new %>
<% end %>

app/views/crawler_fields/update.turbo_stream.erb
<%= turbo_stream.replace :toast do %>
 <%= render "layouts/toast" %>
<% end %>

<%= turbo_stream.replace "crawler_field_#{@crawler_field.to_gid_param}" do %>
  <%= render partial: "item", locals: {
    crawler_field: @crawler_field,
    selected_id: @crawler_field.to_gid_param
  } %>
<% end %>

app/views/dashboard/index.html.erb
<div class="stats shadow w-full" data-theme="coffee">
  <div class="stat">
    <div class="stat-figure text-primary">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 24 24"
        class="inline-block h-8 w-8 stroke-current">
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"></path>
      </svg>
    </div>
    <div class="stat-title">Total Orders</div>
    <div class="stat-value text-primary">25.6K</div>
    <div class="stat-desc">21% more than last month</div>
  </div>

  <div class="stat">
    <div class="stat-figure text-secondary">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 24 24"
        class="inline-block h-8 w-8 stroke-current">
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M13 10V3L4 14h7v7l9-11h-7z"></path>
      </svg>
    </div>
    <div class="stat-title">Page Views</div>
    <div class="stat-value text-secondary">2.6M</div>
    <div class="stat-desc">21% more than last month</div>
  </div>

  <div class="stat">
    <div class="stat-figure text-secondary">
      <div class="avatar online">
        <div class="w-16 rounded-full">
          <img alt="User avatar" src="/avatar.jpg" />
        </div>
      </div>
    </div>
    <div class="stat-value">86%</div>
    <div class="stat-title">Orders done</div>
    <div class="stat-desc text-secondary">31 orders remaining</div>
  </div>
</div>

app/views/exchange_rates/_form.html.erb
<div class="collapse bg-base-100 border border-base-300" data-theme="caramellatte">
   <%= radio_button "exchange-rate-item", nil, nil,
      class: "collapse-radio", checked: exchange.persisted? ? selected_id == exchange&.to_gid_param : true
    %>
  <div class="collapse-title font-semibold" id="exchang-rate-<%= exchange.persisted? ? exchange&.to_gid_param : nil %>">
    <%= exchange.persisted? ? "#{exchange.currency_code} - #{exchange.rate}" : "New Exchange Rate" %>
  </div>
  <div class="collapse-content text-sm">
    <div class="flex flex-row items-center gap-4">
      <fieldset class="fieldset flex flex-1">
        <legend class="fieldset-legend">Country Currency: </legend>
        <%= select_tag "currency_code",
          options_for_select(ExchangeRate::SUPPORTED_CURRENCIES.map(&:upcase), exchange.currency_code),
          class: "input bg-white w-full",
          data: {
            id: exchange.id,
            reflex: "change->ExchangeRate#update_currency_code"
          }
        %>
      </fieldset>
      <fieldset class="fieldset flex flex-1">
        <legend class="fieldset-legend">Rate: </legend>
        <%= text_field_tag "rate",
          exchange.rate,
          class: "input bg-white w-full",
          data: {
            id: exchange.id,
            reflex: "change->ExchangeRate#update_rate"
          }
        %>
      </fieldset>
    </div>
  </div>
</div>

app/views/exchange_rates/index.html.erb
<div class="text-xl font-bold flex items-center justify-between space-x-2 flex-row cursor-default mb-5">
  <div class="flex items-center space-x-2 flex-row">
    <%= icon "dollar-circle" %>
    <span>Exchange Rate</span>
  </div>
  <div>
    <button class="btn" data-reflex="click->ExchangeRate#new">
      <%= icon "plus" %>
      <span>New</span>
    </button>
  </div>
</div>
<div class="space-y-3" id="exchange-rates">
  <%= render partial: "form", collection: ExchangeRate.all, as: :exchange, locals: { selected_id: nil } %>
</div>

<%= turbo_frame_tag :new_exchange_rate_form, class: "mt-3 block" %>

app/views/layouts/_toast.html.erb
<%= turbo_frame_tag :toast do %>
  <div class="toast toast-end">
    <% if alert %>
      <div role="alert" class="alert alert-error alert-soft" data-controller="toast">
        <span><%= alert %>.</span>
      </div>
    <% end %>
    <% if notice %>
      <div role="alert" class="alert alert-success alert-soft" data-controller="toast">
        <span><%= notice %></span>
      </div>
    <% end %>
  </div>
<% end %>